const use = require('./data')
var phone = use.Randomphone()
var name = use.RandomName()
describe('中国大地保险', function() {  
    beforeEach(function() {
            cy.fixture('user.json').as('user')
        })
  it('产品目录', function() { 
    const user = this.user
    cy.visit(user.URL)
    cy.wait(2000)
    cy.contains('天天护家保').click()
    cy.url().should('include', 'groupmessage')
    cy.wait(3000)
    cy.get('#wrapper > div.view.page-transition > main > div.travel-info > div.info-tab-body > div:nth-child(5) > div > div > div > div')
    .click()
    cy.contains('北京').click()
    cy.contains('市辖区').click()
    cy.contains('东城区').click()
    cy.wait(2000)
    cy.contains('立即购买').click()
    cy.get('#wrapper > div.view.page-transition > main > div.policyInfo > div:nth-child(1) > div:nth-child(2) > div > div > input.inputTxt')
    .type(name)
    cy.get('#wrapper > div.view.page-transition > main > div.policyInfo > div:nth-child(1) > div:nth-child(4) > div > div > input.inputTxt')
    .type('11010119900307766X')
    cy.get('#wrapper > div.view.page-transition > main > div > div:nth-child(1) > div:nth-child(6) > div > div > input.inputTxt')
    .type(phone)
    cy.get('#wrapper > div.view.page-transition > main > div > div:nth-child(1) > div:nth-child(7) > div > div > input.inputTxt')
    .type(phone+'@qq.com')
    cy.get('#wrapper > div.view.page-transition > main > div.policyInfo > div:nth-child(3) > div:nth-child(3) > div > div > input.inputTxt')
    .type('北京市西城区阜外大街45号')
    cy.get('#wrapper > div.view.page-transition > main > div.policyInfo > div:nth-child(3) > div:nth-child(4) > div > div > input.inputTxt')
    .type('399921') 
    cy.contains('￥288.00').should(($p) => {
                    expect($p).to.contain('￥288.00') 
                })
    cy.contains('确认信息').click()
    cy.get('#wrapper > div.view.page-transition > main > div.policyInfo > div:nth-child(11) > div > label > i')
    .click()
    cy.contains('确认购买').click()
    cy.wait(15000)
    cy.contains('大地保险支付测试帐号').click()
    cy.wait(8000)
    cy.contains('已完成支付').should(($p) => {
                    expect($p).to.contain('已完成支付')
                })
    })
})