const use = require('./data')
var name = use.RandomName()
var phone = use.Randomphone()
describe('中国大地保险', function() {
    beforeEach(function() {
            cy.fixture('user.json').as('user')
        })
   it('产品目录', function() {
    const user = this.user
    cy.visit(user.URL)
    cy.contains('学平险').click()
    cy.url().should('include', 'groupmessage')
    cy.get('#wrapper > div.view.page-transition > main > div.travel-info > div.info-tab-body > div:nth-child(5) > div > div > div > div')
    .click()
    cy.contains('浙江省').click()
    cy.contains('杭州市').click()
    cy.contains('市辖区').click()
    cy.contains('￥200.00').should(($p) => {
            expect($p).to.contain('￥200.00') 
            })
    cy.contains('立即购买').click()
    cy.get('#wrapper > div.view.page-transition > main > div.policyInfo > div:nth-child(1) > div:nth-child(2) > div > div > input.inputTxt')
    .type(name)
    cy.get('#wrapper > div.view.page-transition > main > div.policyInfo > div:nth-child(1) > div:nth-child(4) > div > div > input.inputTxt')
    .type('120101199003074911')
    cy.get('#wrapper > div.view.page-transition > main > div > div:nth-child(1) > div:nth-child(6) > div > div > input.inputTxt')
    .type(phone)
    cy.get('#wrapper > div.view.page-transition > main > div > div:nth-child(1) > div:nth-child(7) > div > div > input.inputTxt')
    .type(phone+'@qq.com')
    cy.get('#wrapper > div.view.page-transition > main > div.policyInfo > div:nth-child(2) > div:nth-child(3) > div > div > input.inputTxt')
    .type(name)
    cy.get('#wrapper > div.view.page-transition > main > div > div:nth-child(2) > div:nth-child(5) > div > div > input.inputTxt')
    .type('110101201003070556')
    cy.get('#wrapper > div.view.page-transition > main > div > div:nth-child(2) > div:nth-child(7) > div > div > input.inputTxt')
    .type('14789565621')
    cy.get('#wrapper > div.view.page-transition > main > div > div:nth-child(3) > div:nth-child(2) > div > div > input.inputTxt')
    .type('杭州一中')
    cy.get('#wrapper > div.view.page-transition > main > div > div:nth-child(3) > div:nth-child(3) > div > div > input.inputTxt').
    type('高三')
    cy.contains('确认信息').click()
    cy.get('#wrapper > div.view.page-transition > main > div.policyInfo > div:nth-child(10) > div > label > i')
    .click()
    cy.contains('确认购买').click()
    cy.wait(15000)
    cy.contains('大地保险支付测试帐号').click()
    cy.wait(8000)
    cy.contains('已完成支付').should(($p) => {
                    expect($p).to.contain('已完成支付')
                })
})
})